import {
  runVanguardAssistant,
} from "../ai/vanguardAssistant";

import {
  calculateReputation,
} from "../ai/reputationEngine";

import {
  generateRecommendations,
} from "../ai/recommendationEngine";

import {
  GuardianService,
} from "./guardian.service";

export class VanguardAiService {
  static async analyzeUser(
    payload: any,
  ) {
    const result =
      runVanguardAssistant(
        payload,
      );

    if (
      result.riskLevel ===
      "high"
    ) {
      await GuardianService.createAlert(
        {
          userId:
            payload.userId,

          riskScore: 90,

          flags: [
            "High Risk User",
          ],
        },
      );
    }

    return result;
  }

  static async calculateUserReputation(
    payload: any,
  ) {
    return calculateReputation(
      payload,
    );
  }

  static async getRecommendations(
    payload: any,
  ) {
    return generateRecommendations(
      payload,
    );
  }

  static async runGuardianScan(
    payload: any,
  ) {
    const risk =
      await GuardianService.assessRisk(
        payload,
      );

    if (
      risk.riskLevel ===
      "high"
    ) {
      await GuardianService.createFraudCase(
        {
          userId:
            payload.userId,

          caseType:
            "high_risk_user",

          notes:
            "Automatically generated by Guardian AI",
        },
      );
    }

    return risk;
  }

  static async freezeUser(
    userId: number,
    reason: string,
  ) {
    return GuardianService.logAction(
      {
        userId,

        actionType:
          "freeze_account",

        reason,
      },
    );
  }

  static async verifyUser(
    userId: number,
    reason: string,
  ) {
    return GuardianService.logAction(
      {
        userId,

        actionType:
          "verify_user",

        reason,
      },
    );
  }
}