export const ROUTES = {
  HOME: "/",
  FEED: "/",
  MARKETPLACE: "/marketplace",
  LISTING: (id: number | string) => `/listings/${id}`,
  CREATE_LISTING: "/listings/create",
  EDIT_LISTING: (id: number | string) => `/listings/${id}/edit`,
  CHAT: "/chat",
  CONVERSATION: (id: number | string) => `/chat/${id}`,
  WALLET: "/wallet",
  DEPOSIT: "/wallet/deposit",
  WITHDRAW: "/wallet/withdraw",
  ESCROW: "/wallet/escrow",
  PROFILE: "/profile",
  USER_PROFILE: (id: number | string) => `/profile/${id}`,
  SETTINGS: "/settings",
  NOTIFICATIONS: "/notifications",
  SEARCH: "/search",
  AUTH: {
    LOGIN: "/auth/login",
    REGISTER: "/auth/register",
    FORGOT_PASSWORD: "/auth/forgot-password",
  },
  ADMIN: {
    DASHBOARD: "/admin",
    USERS: "/admin/users",
    LISTINGS: "/admin/listings",
    DISPUTES: "/admin/disputes",
    GUARDIAN: "/admin/guardian",
    ANALYTICS: "/admin/analytics",
  },
  GOVERNANCE: "/governance",
  GOVERNANCE_PROPOSAL: (id: number | string) => `/governance/${id}`,
  COMPANY: (id: number | string) => `/companies/${id}`,
  VERIFICATION: "/verification",
  AI: "/ai",
} as const;
